services:
  # TCP server (Bloom Filter)
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    container_name: server
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/data
    stdin_open: true
    tty: true
    depends_on:
      - mongo # Ensure MongoDB is ready before the server starts

  # Web API (Express)
  web:
     build:
       context: .
       dockerfile: Dockerfile.web
     container_name: web
     depends_on:
       - server
       - mongo  # Web API requires MongoDB
     ports:
       - "3000:3000"
     environment:
       - TCP_HOST=server
       - TCP_PORT=8080
       - BF_SIZE=8
       - BF_HASHES=1,2
       - MONGODB_URI=mongodb://mongo:27017/thebestgmail  # Connection string for Mongoose
     volumes:
       - ./src/web_server:/app
       - /app/node_modules
     stdin_open: true
     tty: true
  
  mongo:
    image: mongo:latest
    container_name: bloomly_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db 

  # React frontend
    # frontend:
    #  build:
    #    context: .
    #    dockerfile: Dockerfile.frontend
    #  container_name: frontend
    #  ports:
    #    - "3001:3001"
    #  depends_on:
    #    - web
    #  stdin_open: true
    #  tty: true

# Named volumes
volumes:
  mongo_data:
